# Generated by Django 4.2.4 on 2023-09-04 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saas', '0003_product_review_count_product_star_rating'),
    ]

    operations = [
        migrations.CreateModel(
            name='AliexpressProducts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
