# Generated by Django 4.2.4 on 2023-09-04 03:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('saas', '0004_aliexpressproducts'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AliexpressProducts',
            new_name='AliexpressProduct',
        ),
    ]
